---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Why do poor people make bad decisions"
subtitle: ""
summary: "The experience of scarcity reduces mental bandwidth"
authors: [admin]
tags: [poverty, economics]
categories: [poverty, economics]
date: 2014-08-20
lastmod: 2014-08-20
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

In their new book, _Scarcity: Why Having Too Little Means So Much_, economist Sendhil Mullainathan and psychologist Eldar Shafir team up to tackle the question of how scarcity impacts decision-making behavior. Scarcity of money can actually cause poor decisions, as can scarcity of time, calories, or friends. The remarkable finding of the book is just how consistently the same mechanisms influence our decisions under scarcity regardless of what resource we lack. I'm more interested in poverty than in helping you figure out how a diet (scarcity of calories) influences your behavior or how to manage your time - this is a policy blog, not self-help! - but the influence of scarcity across multiple types of resources and in both observational and experimental settings increases the credibility of their findings on poverty.

Mullainathan and Shafir focus on two key psychological mechanisms by which scarcity impacts decision making:

- Mental Bandwidth
- Focusing and Tunneling

Under conditions of scarcity, our minds are unconsciously captured by the object of scarcity - be it money, time, calories, etc. If you are hungry enough, you will literally be unable to think about things other than food, and if a psychologists flashed words on a screen, it would take you significantly less time to process the food-related words than the other words. Mental bandwidth influences both intelligence and self-control. And, of course, it has more serious implications than word recognition, as Mullainathan and Shafir point out:

>...scarcity reduces all these components of bandwidth - it makes us less insightful, less forward-thinking, less controlled. And the effects are large. Being poor, for example, reduces a person's cognitive capacity more than going one full night without sleep. It is not that the poor have less bandwidth as individuals. _Rather, it is that the experience of poverty reduces anyone's bandwidth._

Scarcity also leads to a pattern of focusing and tunneling. Focusing by itself can be a good thing, the boost of productivity brought on by the deadline for a project at work. The poor are actually less likely to fall for what behavioral economists term economic illusions. For most people, changing the context in which an object is bought will change behavior - e.g. people will drive across town to save $25 on a $50 item, but won't drive across town to save $25 on a $1,000 item. The poor, by contrast, have a better idea of exactly what $25 is worth to them, and so would behave the same way in both cases, reasoning that a trip across town is either worth $25 or it isn't.

This implies, as the authors note, "In the near-term, the poor are more economically rational than the rest of us. 'The poor in these studies behave more 'rationally.' They are closer in this case to the rational economic ideal, closer to homo economicus.'"

There is, however, a price to be paid for focus. Focusing in on one thing to the exclusion of other factors is tunnel vision, and tunneling helps to explain bad economic decisions - at least, they seem bad if you're standing outside the tunnel.

There are more payday loan stores in the U.S. than McDonald's and Starbucks combined, and they extract 3.5 billion in fees each year. Borrowers quickly become trapped in a cycle of debt, resorting to payday loans in order to make ends meet inside the tunnel and then paying the price later. Mullainathan and Shafir argue that,"...the reason the poor borrow is poverty itself. No need to resort to myopia or to financial ineptitude for an explanation. Predatory lenders may certainly facilitate this type of borrowing, but they are not the source."

Poverty itself becomes a scarcity trap, with its influence reaching into all corners of life, including financial processes, intelligence, and self-control. Summing up the situation for the poor with a thought experiment, the authors write:

> So if you want to understand the poor, imagine yourself with your mind elsewhere. You did not sleep much the night before. You find it hard to think clearly. Self-control feels like a challenge. You are distracted and easily perturbed. And this happens every day. On top the other material challenges poverty brings, it also brings a mental one.

## Escaping the Scarcity Trap

The good news is that this view of scarcity causing poverty is actually less bleak than the dominate alternative view in which poverty is the result of individual lack of intelligence, self-control, marketable skills, etc. If, instead, scarcity is the problem, then we can work on designing institutions that prevent scarcity. In combating scarcity the key concept to keep in mind is slack. The presence of slack allows individuals and organizations to overcome inevitable minor disruptions. A budget with slack can prevent tunneling, and thus short-circuit the demand for payday loans.

Mullainathan and Shafir point to three policy solutions that could help to introduce slack: free/affordable child care, consistent work hours, and affordable microloans. The benefits of these programs reach far beyond what program evaluators usually measure, the authors argue:

>Child care provides much more than just child care, and the right financial product does much more than just create savings for a rainy day. Each of these can liberate bandwidth, boost IQ, firm up self-control, enhance clarity of thinking, and even improve sleep. Far-fetched? The data suggest not.
