---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Lutherans in the Public Sphere"
subtitle: "A trilingual approach"
summary: ""
authors: [admin]
tags: [lutheran, religion, sermon, activism]
categories: [Religion, Sermon]
date: 2012-10-21
lastmod: 2012-10-21
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

When I was a sophomore in college I had the opportunity to study abroad in Mexico. I remember meeting my homestay parents for the first time. At some point, they asked me what my favorite sport was. For the life of me, I don’t know why I didn't just say basketball or soccer, two sports that I like, and more importantly, two sports that I know how to say in Spanish. But no, I decided to attempt to explain… ultimate Frisbee. Now, at least back then, ultimate Frisbee was not popular in that part of Mexico. My Spanish was not that good, and I wound up using the same word for “Frisbee” that is used for CDs. So my family’s first impression may have been that my favorite sport is a bunch of people running around a field throwing music at each other.

When I was trying to tell my homestay family about ultimate Frisbee, I found myself lacking the proper vocabulary. I didn't speak the language well, and so my attempts to communicate were ineffective, and potentially comical.

In recent years it can sometimes feel as though Christians have also forgotten or failed to learn how to communicate with others about their faith. Some have clung intensely to a literal interpretation of the scripture and to an almost theocratic vision of society. Others have chosen to paint Jesus as solely a great teacher and a wonderful example. Still others have spiritualized the Gospel, making its message solely about prayer and the afterlife. I’m sure you’ve all heard at least once during this political campaign season that the Church should confine itself to the spiritual, and not be involved in the political.

This morning, I am going to suggest to you, that a Church that is not in some way political is failing to live out an important part of the Gospel. First, we need to understand that to be political is not the same thing as to be partisan. To be political simply means to be involved in the way in which we order our communities. To be political is to pursue a just social order. The church may not have much to say about Republicans or Democrats, but if it is to be faithful to its mission as the body of Christ, it will certainly need to have a lot to say about justice.

Second, we need to figure out how Christianity can inform our politics in an age of religious pluralism. The United States is not and should not be a theocracy, so how are Christians to engage in political discourse?

I opened the sermon by talking about my poor attempts to speak Spanish not only because I thought you might enjoy a story about me making a fool of myself, but also because I want to make a broader point about vocabulary and language. The theologian Glen Stassen suggests that Christians should be fluent in three sets of vocabulary, or three languages. Christians should be able to speak in the language of faith, the language of reason, and the language of experience.

Like any language, the language of faith is one that must be learned and that improves only by means of practice, and by talking with others who share that language. This perhaps, is why Pastor Steven has placed a continual emphasis on the importance of education and biblical literacy for both youth and adults.

The language of faith shapes us and draws us together as a Christian community. It is a shared vocabulary of institutional and cultural memories and stories that give our life together a narrative cohesion and unity. We are part of the story of God’s people, and the language of faith is the history of our relationship with God.

The language of faith pushes us into the public sphere because the language of faith is a language of love; and if you love someone, you don’t leave them to suffer injustice. Justice is the concrete, physical, and tangible sign of God’s love. The Peruvian theologian Gustavo Gutierrez writes that “the Gospel, precisely insofar as it is a message of total love, has an inescapable political dimension, because it is addressed to people who live in a fabric of social relationships,”

Cornel West puts it succinctly and memorably when he intones, “Justice is what love looks like in public.”

Within our own denomination, the ELCA Church in Society statement affirms that, “The Gospel does not take the Church out of the world, but instead calls It to affirm and to enter more deeply into the world. Although in bondage to sin and death, the world is God’s good creation, where, because of love, God in Jesus Christ became flesh. The Church and the world have a common destiny in the reign of God. The Church acts for the sake of the world in hope and prayer: “Your kingdom come, your will be done, on earth as it is in heaven.”

The language of faith is not only a spoken language; it is also a ritual and symbolic language. When we say the Lord’s prayer, and when we share the Lord’s Supper, we are united together around the Lord’s table in memory of a God who loves us so much that God refused to leave us in a state of brokenness and sin, but instead took on human form and loved us even to the point of death on a cross. The language of faith is a language of justice. Ritual and scripture affirm God’s desire for a just social order that reflects a restoration of our relationship with God, and with each other.

In the Third Lutheran Church Mission Statement we say that part of our mission is to live in relationship “with the community, near and far, by being intentionally present as a sign of God’s love in a broken world.” To be a sign of God’s love means to work for justice here in Louisville; and around the world.

This, then, is the language of faith, a language of shared stories and symbols that unite us together and inform our shared mission into the world.

As wonderful and rich as the language of faith is, it does have limitations. The language of faith does not tell us everything we need to know about our current society; and within a pluralistic democracy the language of faith is not always the appropriate language for advocacy. This is why Christians must also be fluent in the language of reason.

The ELCA statement on Church and Society affirms that, “Transformed by faith, this church in its deliberation draws upon the God-given abilities of human beings to will, to reason, and to feel. This church is open to learn from the experience, knowledge, and imagination of all people, in order to have the best possible information and understanding of today’s world. To act justly and effectively, this church needs to analyze social and environmental issues critically and to probe the reasons why the situation is as it is.”

For the past few weeks, Third Lutheran has been talking about becoming involved with a local organization here in Louisville called CLOUT, Citizens of Louisville Organized and Uniting Together. CLOUT brings together churches all over Louisville to advocate for specific policy changes that improve Louisville and get to the root causes of injustice in our community. One of the things CLOUT does extremely well is to do the research on an issue and then come up with a specific policy change that they advocate for. The language of faith informs their desire to seek justice, but it is reason that identifies and analyzes ways to correct injustice.

Reason too has limitations. The psychologist Jonathan Haidt compares reason to a trial lawyer or press secretary. No matter what you may say to a press secretary or lawyer, they are never going to come out and say, “You know what, I think the President is actually just completely wrong on this one” or “yeah, my client’s guilty, you got us.” As much as we might like to think otherwise, we’re usually not any more open to being persuaded by reason than that lawyer or press secretary. Reason is very good at coming up with solutions, but it’s not particularly motivational and it’s also not persuasive.

To really get through to people, it is essential to speak the language of experience. In my junior year of college I studied abroad in Nicaragua for three weeks. I went with the organization Witness for Peace, the same organization that brought Itzel and Lariza here this morning to speak to us before church. Before the trip it was constantly being billed as life-changing. I recall even being annoyed at how high the expectations were going into it. You see, I thought I knew what I would find there; that I knew the statistics and that after doing the pre-reading assigned for the course I had a pretty good idea of what to expect. I was wrong. Not exactly about what I’d find, but about how it would affect me. I had seen Nicaragua through the language of reason, but for those three weeks I felt it through the language of experience. And that changed me. It is no exaggeration to say that I would not be a part of this church and be here today preaching if I had not been to Nicaragua.

The experiences of the Israelites in the Bible change them as well. The Old Testament is full of God telling the Israelites, remember the alien or remember the slave and treat them well…because you were once slaves and aliens in the land of Egypt. More recently, the history of human rights has largely been a reaction to the experience of suffering. It is no coincidence that the United Nations Declaration of Human Rights was signed just three years after the horrors of World War II.

The Jewish philosopher Emmanuel Levinas holds that the core of ethics lies in the experience of the face to face encounter with another person. Once we have seen the face of the other and acknowledged their humanity and their suffering we are ethically bound to them and we cannot walk away. The Christian Gospel goes a step farther in the parable of judgment in the 25th chapter of Matthew. Not only is the core ethical responsibility in the parable to respond to the needs of the naked, the hungry, and the prisoner, but we find that in doing so we have come face to face not only with the other, but also with the divine. We find that whatever we have done unto those in need we have done to Jesus himself.

The task before us as Christians in a modern pluralistic democracy is a difficult one; but it is not impossible. The language of faith informs our concern for justice and grounds us in community and in relationship with God and each other. The language of reason allows us to make our case to the broader community and to find the root causes of the injustices that leave people in pain. And the language of experience reminds us that as we come face to face with other human beings we cannot walk away from them; and that if we accept the challenge of acknowledging the needs of others we may find ourselves face to face not only with another human being; but with God.

Amen.
