---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Citizens in a Market Driven State"
subtitle: ""
summary: ""
authors: [admin]
tags: [markets, citizens]
categories: [Philosophy]
date: 2013-07-09
lastmod: 2013-07-09
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

As the state become increasingly market-driven, the meaning of citizenship is changing. From Disciplining the Poor:

>As the state is privatized, so too are the social problems of the citizenry. Matters of shared consequence, once addressed through public decisions about how to organize collective life, are recast as personal problems to be solved through rational individual choices. The democratic citizen, positioned as one who must act in concert with others to achieve preferred outcomes, is redefined as a consumer, worker, and taxpaying customer of the state. Citizens, in this guise, are investors who have a contractual right to expect efficient state services that produce returns. They are repositioned, through vouchers and choice programs, as individual consumers who pursue better outcomes by seeking goods from other providers (exit) rather than as co-participants deliberating and acting together to improve their shared institutions (voice). They are encouraged to help others, not by deciding how to organize their communities in a just manner, but by pursuing individual work as volunteers, charitable givers, and virtuous providers of services (Crenson and Ginsberg 2002). The competent and self-reliant market actor - working, investing, choosing, and assessing returns - is made synonymous with the good citizen.

There are lots of implications of this shift, but I'll stick with three quick ones:

1. The individual who fails as an economic actor fails also as a moral and civic one. This is a problem, because perfectly nice and wonderful people can be terrible economic actors. Our current economic system can at times reward excessive risk taking as well as greed and a general lack of concern for others.
2. Social problems are viewed through the prism of individual choice. The emphasis become placed on why individuals drop out of school and not why the school system has so many drop-outs. The increasingly unhealthy diet and exercise patterns across the U.S. is another excellent example. Instead of reflecting on the inevitable result of a culture that bombards us with advertising and the availability of sugars and fats that we are genetically programmed to desire, we blame individuals for lacking self-discipline.
3. The state becomes paternalistic in an effort to form disciplined market actors and increase market efficiency. This is part of why welfare, which was historically designed to allow single women to stay home and raise children was transformed into workfare. The goal of the state becomes to encourage work, increase GDP, reduce unemployment etc. etc. The citizen as a member of a community collectively deliberating for the common good is lost and replaced by the individual economic actor who is formed to meet state and market goals.
