---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Why the narrative of personal responsibility slips so easily into racism"
subtitle: ""
summary: ""
authors: [admin]
tags: [race]
categories: [race]
date: 2015-08-03
lastmod: 2015-08-03
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

When it comes to explaining poverty and inequality in the U.S., there tend to be two broad categories of explanations. The first is personal responsibility. On this narrative, poverty and inequality are caused by personal failings. The second focuses on institutional factors, arguing that poverty is a result of the choices we've made about the structures of our political and economic institutions.

The continued existence of racial inequality poses a serious dilemma for the narrative of personal responsibility. In the United States, there is a large racial gap in wealth, and it hasn't been shrinking over time.

The narrative of personal responsibility remains a popular explanation among conservatives, and some conservative outlets like the Wall Street Journal have even gone so far as to declare an end to institutional racism. But can personal responsibility really explain the racial wealth gap?

For any given individual it's easy enough to find shortcomings that explain why they didn't graduate high school or why they wound up in or near poverty. But if we want to explain why blacks, as a group, are not as wealthy as whites, then we're left with two options. For personal responsibility to explain the wealth gap, it's not enough to say an individual failed to live up to their responsibility, one would have to claim that blacks, as a group, are less likely to live up to their responsibilities than whites. Less likely to try hard to get a good education. Less likely to make the financial choices that lead to wealth accumulation. But, of course, to say that blacks, as a group, are less responsible, is the very definition of racism - it's attributing a negative trait to an entire race.

Next time someone tells you the poor need to pull themselves up by their own bootstraps, ask them why blacks, according to the data on wealth, are so much worse at this bootstrap pull than whites. Could it be that centuries of slavery, a hundred years of legal discrimination, and decades of ongoing de facto discrimination have left them without bootstraps?

The other explanation for poverty and racial inequality is institutional/structural. This explanation enjoys two major advantages. First, it can explain group-level outcomes without recourse to the idea that those outcomes must be driven by innate differences between the groups. Instead, they could be driven by institutional differences in the way the groups are treated. Second, There's a lot of evidence on how our past and present political and economic institutions are leading to racial disparities.

For an overview of institutional discrimination, I highly recommend Ta-Nehisi Coates' lengthy feature article in the Atlantic, "The Case for Reparations." There's also a good feature on the history of voting rights and the ongoing effort to role them back in last week's New York Times Magazine. And here's a shorter piece from Vox on how the school system's racial biases create a gap in educational achievement by pushing black students out of the school system and into the criminal justice system.

For book-length treatments, I highly recommend Michelle Alexander's The New Jim Crow, which traces the history of how institutions were transformed at the end of the Jim Crow era in ways that made discrimination less visible but did not eliminate it. For an academic approach, I recommend Disciplining the Poor, by Soss, Fording, and Schram.

Finally, it's worth highlighting one of the more obvious and direct ways in which discrimination persists. Black applicants find themselves at a severe disadvantage in the labor market. Economists Marianne Bertrand and Sendhil Mullainathan tested this by sending out resumes that differed only in the name at the top, comparing Greg Baker and Emily Walsh to Jamal Jones and Lakisha Washington. They found that Greg and Emily received 50 percent more callbacks for interviews than Jamal and Lakisha.

So where does this leave personal responsibility? It's not wrong to encourage individuals to be responsible and to make good choices. It is wrong to suggest that individual choices are the only things that determine individual outcomes, and it's very wrong to suggest that individual choices determine group-level outcomes. For example, telling a high school student (who you personally know) that they should still try to graduate from high school even in an unfair school system is a good thing to do. Ideally, you'd also encourage them to work with others to change the school system.

The problem is when personal responsibility is used as something to be preached to others - to people you don't know - and used as an excuse not to work for just institutions. Personal responsibility can't explain all the outcomes that we see in society, and in particular it can't explain the vast chasm or racial inequality in the U.S. today. Structures and institutions matter. The good news is that it's in our power to change them.
