---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Adam Smith and 'those who live by profit'"
subtitle: ""
summary: ""
authors: [admin]
tags: [smith, economics, policy]
categories: [Adam Smith, Economics, Public Policy]
date: 2013-08-24
lastmod: 2013-08-24
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

In Adam Smith’s classic book “The Wealth of Nations” he argues that the production of a country can be divided into three parts: the rent of land; the wages of labour; and the profits of stock. He argues that these parts produce revenue “to three different orders of people; to those who live by rent, to those who live by wages, and to those who live by profit.”

Smith argues that the first two will generally act in the interest of society if they are well educated and understand their long-term interests. A strong all-around society means increased productivity with the same amount of land, thus increasing the rent for those who live by rent. Similarly, a strong society means a tight labor market and increased wages for those who live by wages. However, Smith urges caution against setting public policy based on the input of those who live by profit,

>The plans and projects of the employers of stock [capital] regulate and direct all the most important operation of labour, and profit is the end proposed by all those plans and projects. But the rate of profit does not, like rent and wages, rise with the prosperity, and fall with the declension of society. On the contrary, it is naturally low in rich, and high in poor countries, and it is always highest in the countries which are going fastest to ruin. The interest of this third order, therefore, has not the same connexion with the general interest of the society, as that of the other two.

Smith is certainly oversimplifying (to be fair, it was actually simpler in 1776), but the general point remains true today. There is a lot of opportunity for profit in poor economies, and we tend to see massive amounts of inequality as a result. Smith argues that those who control the capital (which Smith calls stock) are able to impose on others because they have “persuaded him to give up both his own interest and that of the public, from a very simple but honest conviction, that their interest, and not his, was the interest of the public.”

I think here Smith has cut to the very heart of what we sometimes call class warfare today. For the most part it seems to consist of an effort by the owners of capital to convince everyone else that their interest is actually the interest of the public. To be sure, there are certainly places where these overlap (adequately investing in infrastructure, education, and R&D for instance) but they are not entirely the same thing (for instance, figuring out who pays for all of this investment). Smith closes Book I with a strong warning:

>The proposal of any new law or regulation of commerce which comes from this order, ought always to be listened to with great precaution, and ought never to be adopted till after having been long and carefully examined, not only with the most scrupulous, but with the most suspicious attention. It comes from an order of men, whose interest is never exactly the same with that of the public, and who accordingly have, upon many occasions, both deceived and oppressed it.
