---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Market Norms are crowding out Social Norms"
subtitle: "And society is poorer as a result"
summary: "Market norms differ from social norms and our society has been moving in the direction of embracing market norms even in non-market arenas."
authors: [admin]
tags: [economics, philosophy, norms, policy, ethics, Sandel]
categories: [philosophy, public policy, economics]
date: 2013-07-23
lastmod: 2013-07-23
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---


Imagine you are going over to a friend’s house for a nice dinner. You want to show appreciation for the lovely meal they’ve prepared for you, and you have a few options. You can offer to have them over for dinner in the future. You can bring a bottle of wine or a six pack of beer. You can simply say thank you and tell them what a lovely evening you have had. The one thing you would not want to do is offer to pay them the fair market value of the food and ambiance they have prepared for you. This would be a major social faux pas, the replacing of a social norm with a market interaction.

There are some situations that are governed by social norms and other situations that are governed by market norms. To an economist, however, if those norms ever do overlap, then they could only strengthen each other. After all, if someone is willing to do something based only on the strength of a social norm, shouldn’t they be more willing to do it for both the social norm and the additional monetary reward of the market? To be more concrete about it, if lawyers are willing to volunteer their time to help the elderly with legal analysis, it would be completely irrational for them to not be at least as willing to sell their time at a discount.

As it turns out, in many situations market norms don’t complement social norms, they crowd them out. The AARP really did ask some lawyers if they would offer services to retirees at a discount. The lawyers said no. Then the AARP asked if they would do it for free and they said yes. Now the economically rational thing to do would be for them to think of themselves as volunteers who get paid a small stipend, but once market norms were part of the consideration, social norms departed.

In _Predictably Irrational_, Dan Ariely writes about an experiment he set up to test market norms and social norms. Participants were asked to complete a mind-numbingly dull computer task, dragging circles into a square for 5 minutes. They split their participants into three groups, one group received 5 dollars, one group 50 cents, and one group was simply asked to complete the task as a favor to the experimenters. Those making 5 dollars outperformed those making only 50 cents by a wide margin, 159 to 101. The volunteers, however, dragged 168 circles. To be clear, that’s not significantly more than the 5 dollar group. If you pay people a reasonable wage to do a task they really will work hard at it. The point, however, is that the social norm was every bit as strong as the fair wage norm, and much, much stronger than the market norm created by offering substandard compensation.

One other concrete example of this crowding out of social norms comes from an Israeli daycare. The daycare decided to implement a fine on parents who were late to pick up their children. The fine backfired in epic fashion, and the number of parents who were late actually increased. Before, the parents felt bound by a social norm. Having worked in after-school care I can tell you that parents really do feel bad about inconveniencing the staff by being late. Once money enters the equation, however, being late is simply an extra service that can be paid for and falls under the realm of market norms.

The most disturbing part of the day care story is what happened next. The day care, realizing that the fine wasn’t working, decided to eliminate it. The parents behavior, however, did not revert to prior levels of lateness, in fact, it rose a little bit. Now that the social norm was gone it did not return, and having eliminated the market penalty as well it makes sense that tardiness increased. Once market norms have crowded out social norms it may not be easy to get them back.

It turns out that being exposed to market cues and signals  has a negative effect on our social behavior. Psychologist use a technique called priming to see how certain unconscious cues affect our behavior. Priming works by exposing its subjects to something that will later impact their thinking. In this case, subjects were exposed to something money-related, i.e. a stack of monopoly money on a table or a computer screen saver with dollar bills floating in the water. Money primed people become more self-reliant, but also more selfish and less willing to help others. They were less social and showed an increased desire to be left alone. 

Michael Sandel writes about the moral implications of our transition to a market driven society in _What Money Can’t Buy_:

>when we decide that certain goods may be bought and sold, we decide, at least implicitly, that it is appropriate to treat them as commodities, as instruments of profit and use. But not all goods are properly valued in this way.

The problem is that over time, and without ever really discussing it,

>…we drifted from having a market economy to being a market society. The difference is this: A market economy is a tool – for organizing productive activity. A market society is a way of life in which market values seep into every aspect of human endeavor. It’s a place where social relations are made over in the image of the market.

Now, a market economy is a good way to regulate the sales of books, clothing, shoes, technology, and a great many other things. But it’s not a good way to live a full and flourishing life as a human being. My problem is not with markets, but rather with a series of assumptions that associates human well-being with market well-being, as though the two were the same thing. For now let me conclude with some wise words from Robert F. Kennedy, who recognized this problem back in 1968:

>Our  Gross National Product is now over 800 billion dollars a year. But that Gross National Product counts air pollution and cigarette advertising, and ambulances to clear our highways of carnage. It counts special locks for our doors and the jails for the people who break them. It counts the destruction of the redwood and the loss of our natural wonder in chaotic sprawl. It counts napalm and counts nuclear warheads and armored cars for the police to fight the riots in our cities. It counts…the television programs which glorify violence in order to sell toys to our children. Yet the Gross National Product does not allow for the health of our children, the quality of their education or the joy of their play. It does not include the beauty of our poetry or the strength of our marriages, the intelligence of our public debate or the integrity of our public officials. It measures neither our wit nor our courage, neither our wisdom nor our learning, neither our compassion nor our devotion to our country. It measures everything, in short, except that which makes life worthwhile.

Note: This was originally posted on [Rgumentative](https://natewkratzer.wordpress.com/2013/07/23/market-norms-are-crowding-out-social-norms-and-society-is-poorer-as-a-result/), my previous blog
