---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Jayber Crow by Wendell Berry"
subtitle: ""
summary: ""
authors: [admin]
tags: [books, berry, jayber crow]
categories: [Books, Berry]
date: 2013-10-05
lastmod: 2013-10-05
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

Wendell Berry’s fictional novel, Jayber Crow, provides a number of interesting passages that relate well to the major themes of this blog.

Jayber is the barber (and church janitor) in Port William, the fictional small Kentucky town that serves as the setting for most of Berry’s fiction.  As a child at a religious orphanage, Jayber winds up going to seminary. There, he begins to have theological questions and doubts that most of his professors are unprepared to answer. Finally, he asks his intimidating New Testament Professor. In the conversation he realizes that he is not going to continue at seminary and become a pastor. The excerpt below starts with Jayber speaking:

>“I had this feeling maybe I had been called.”

>“And you may have been right. But not to what you thought. Not to what you think. You have been given questions to which you cannot be given answers. You will have to live them out – perhaps a little at a time.”

>“And how long is that going to take?”

>“I don’t know. As long as you live, perhaps.”

>“That could be a long time.”

>“I will tell you a further mystery,” he said, “It may take longer.”

There is a certain value to questions that can only be answered by living them out. Intriguingly, even the mystery of how living out the questions can extend beyond our individual lifetimes is not necessarily a reference to some sort of individual salvation. Instead, it relates to finding one’s place within a larger community:

>My vision of the gathered church that had come to me after I became the janitor had been replaced by a vision of the gathered community. What I saw now was the community imperfect and irresolute but held together by the frayed and always fraying, incomplete and yet ever-holding bonds of various sorts of affection. There had maybe never been anybody who had not been loved by somebody, who had been loved by somebody else, and so on and on. … It was a community always disappointed in itself, disappointing its members, always trying to contain its divisions and gentle its meanness, always failing and yet always preserving a sort of will toward goodwill. I knew that, in the midst of all the ignorance and error, this was a membership; it was the membership of Port William and of no other place on earth. My vision gathered the community as it never has been and never will be gathered in this world of time, for the community must always be marred by members who are indifferent to it or against it, who are nonetheless its members and maybe nonetheless essential to it. And yet I saw them all as somehow perfected, beyond time, by one another’s love, compassion, and forgiveness, as it is said we maybe be perfected by grace.

Jayber also had a fair amount to say about Christian love in times of war:

>I knew too that this new war was not even new but was only the old one come again. And what caused it? It was caused, I thought, by people failing to love one another, failing to love their enemies. I was glad enough that I had not become a preacher, and so would not have to go through a war pretending that Jesus had not told us to love our enemies.

>The thought of loving your enemies is the opposite to war. You don’t have to do it; you don’t have to love one another. All you have to do is keep the thought in mind and Port William becomes visible, and you see its faces and know what it has to lose. Maybe you don’t have to love your enemies. Maybe you just have to act like you do. And maybe you have to start early.

He also recognizes his own failures. This scene is set at Jayber’s barbershop during the Vietnam war.

>One Saturday evening, while Troy was waiting his turn in the chair, the subject was started and Troy said – it was about the third thing said – “They ought to round up every one of them sons of bitches and put them right in front of the damned communists, and then whoever killed who, it would be all to the good.”

>There was a little pause after that. Nobody wanted to try to top it. I thought of Athey’s reply to Hiram Hench.

>It was hard to do, but I quit cutting hair and looked at Troy. I said, “Love your enemies, bless them that curse you, do good to them that hate you.”

>Troy jerked his head up and widened his eyes at me. “Where did you get that crap?”

>I said, “Jesus Christ.”

>And Troy said, “Oh.”

It would have been a great moment in the history of Christianity, except that I did not love Troy.

In Wendell Berry’s stories about Port William, one hears more than a simple story about small town life. Berry is part of an ethical project, one that revolves around story-telling. Alasdair MacIntyre’s After Virtue lays out a central role for stories in the way in which human beings find their ethical compass by placing themselves within stories. If MacIntyre is the philosopher for this conception of narrative ethics, Berry seems to be its storyteller, preserving for smalltown Kentucky what MacIntyre refers to as, “the stock of stories which constitute its initial dramatic resources.”

I’ll close with a little bit more from MacIntyre on the importance of stories to ethical action:

>A central thesis then begins to emerge: man is in his actions and practice, as well as in his fictions, essentially a story-telling animal. He is not essentially, but becomes through his history, a teller of stories that aspire to truth. But the key question for men is not about their own authorship. I can only answer the question ‘What am I to do?’ if I can answer the prior question ‘Of what story or stories do I find myself a part?’ We enter human society, that is, with one or more imputed characters – roles into which we have been drafted – and we have to learn what they are in order to understand how others respond to us and how our responses to them are apt to be construed. It is through hearing stories about wicked stepmothers, lost children, good but misguided kings, wolves that suckle twin boys, youngest sons who receive no inheritance but must make their own way in the world and eldest sons who waste their inheritance on riotous living and go into exile to live with the swine, that children learn or mislearn what a child and what a parent is, what the cast of characters may be in the drama into which they have been born and what the ways of the world are. Deprive children of stories and you leave them unscripted, anxious stutterers in their actions as in their words. Hence there is no way to give us an understanding of any society, including our own, except through the stock of stories which constitute its initial dramatic resources.
