---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Facts, Values, Economics, and Experience"
subtitle: ""
summary: ""
authors: [admin]
tags: [values, economics, experience, sen, putnam, Schumacher]
categories: [Economics, Values, Epistemology]
date: 2014-01-28
lastmod: 2014-01-28
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

Economists like to think of much of their work as a scientific description of the world, free of moral or ethical content. The people who write and think about ethics and economics are engaged in normative economics, while those who describe the world as it is practice positive economics.

However, the very practice of positive economics comes from a series of philosophical assumptions about what constitutes knowledge. At a very basic level those assumptions hold that (1) statements about reality can be classified as true or false; and that (2) social processes, like physical processes, are governed by a set of laws that can, in theory, be known, even if in practice we do not have sufficient data to derive them.

Positive economics then relies heavily on statistical methodology and experimentation in its empirical work, and in theoretical work assumes that individuals act rationally and out of self-interest (subject to incomplete information and individual bias). This allows the work to proceed without making it clear that anything has been presupposed about ethics. Even when it comes to things like considering social well-being economists have done their best to draw up a value-neutral criterion of efficiency.

One of the ironies is that while economists have attempted to scrub their work of ethical values they have continued to employ epistemic values (coherence, precision, clarity, etc.) and have become quite attached to aesthetic values like elegance and parsimony in mathematical modeling.

In our experience, facts and values are actually entangled, woven together in a way that eventually reduces a strict positivist to being stuck in a language game, a situation in which the rules governing the use of language are precise and well-defined, but the language has no relationship to the reality of our experience. It is perhaps a bit like mistaking a game of chess for an actual war. Having deduced clear rules and precise values and movements for each piece, one finds that instead of having brought precision to reality they have instead constructed a game. Reality is simply not as precise and orderly as we would like.

Much of our actual language is characterized by what Hillary Putnam calls ‘thick moral terms’, words such as cruel, passionate, working-age, etc. If I say that Emperor Nero was cruel, I am simultaneously asserting a set of historical facts (Nero persecuted and killed a large number of people) and saying that those historical facts merit a judgment of cruelty. Indeed, for almost any of our perceptions about the world there is a combination of empirical facts and a value judgment about those facts. Absent a complete list of every fact there is no way around this. Returning to our example of Emperor Nero, one could attempt to list everything Nero every did, but this listing would take up a lifetime. Even if one wanted to debate whether or not he was cruel one would first have to narrow down which facts were relevant for that judgment.

Turning more specifically to economics, phrases like working-age population, labor market, efficiency, self-interest, rational, etc. all imply some ordering of raw data, a combination of data and judgment. The selection of which topics to study, from whose perspective, and with what data are not value neutral. Nor is there anyway that they could be. Immersed as we are in reality, human beings don’t have the luxury of ever being a completely detached neutral observer, nor do we have the mental capacity to process that much information without intervening value judgments.

The rejection of a purely positive approach in favor of one that recognizes the unavoidable entanglement of facts and values does not mean that we are lost in a sea of relativism and unable to do anything about it. As E.F. Schumacher put it in his classic book *Small is Beautiful: Economics as if People Mattered*:

>All subjects, no matter how specialized, are connected with a centre; they are like rays emanating from a sun. The centre is constituted by our most basic convictions, by those ideas which really have the power to move us. In other words, the centre consists of metaphysics and ethics, of ideas that – whether we like it or not – transcend the world of facts. Because they transcend the world of facts, they cannot be proved or disproved by ordinary scientific method. But that does not mean that they are purely “subjective” or “relative” or mere arbitrary conventions. They must be true to reality, although they transcend the world of facts – an apparent paradox to our positivist thinkers. If they are not true to reality, the adherence to such a set of ideas must inevitably lead to disaster.

The key point here is that the way we process information across a wide array of disciplines will be largely determined by our ethical and metaphysical presumptions. The good news is that those presumptions are not randomly chosen. While facts being entangled with values is perhaps frightening to the positivist thinker, there is a hidden upside. Values are also entangled with facts. Hillary Putnam describes the work of the pragmatist John Dewey in The Collapse of the Fact/Value Dichotomy:

>For [Dewey] “inquiry” in the widest sense, that is human dealings with problematical situations, involves incessant reconsideration of both means and ends; it is not the case that each person’s goals are cast in concrete in the form of a “rational preference function” that is somehow mysteriously embedded in his or her individual mind, or that all we are allowed to do as long as we are “rational” is look for more efficient means to these immutable but idiosyncratic goals or values. Any inquiry has both “factual” presuppositions, including presuppositions as to the efficiency of various means to various ends, and “value” presuppositions, and if resolving our problem is difficult, then we may well want to reconsider both our factual assumptions and our goals….*Dewey is really talking about learning through experimentation and discussion how to increase the amount of good in our lives.*

Within the field of economics, no one has done a better job of this than Amartya Sen. Sen, who won a Nobel for his work on famine relief, has been engaged in re-examining the end-goals of economic growth. Sen has persuasively argued that one can judge a theory of justice based on the information that it considers relevant. For utilitarians that is only utility, for libertarians it is procedural liberty, etc. Sen argues that because human beings hold values that are more complex than either utility or freedom from undue interference an appropriate theory of well-being must include multiple indicators including health, education, life-expectancy, social connectedness, economic and political freedoms, economic well-being, etc.  and be based around the capability of people to choose a life worth living.

Sen’s approach deserves much more attention than I can give it here, but his larger point is that there is no way to avoid the political and democratic process of weighing certain types of goods against others. Traditional welfare economics has attempted to dodge this central question by concerning itself primarily with questions of deadweight loss and Pareto efficiency. Sen writes,

>…if there is to be such a subject as welfare economics at all, and in particular, if welfare economics is to speak to problems of poverty and other forms of deprivation, then welfare economics cannot avoid substantive ethical questions.
