---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "What I Believe"
subtitle: ""
summary: "An account of my view on religion at the time of writing. Also gets into relativism/universalism and what it means for something to be true."
authors: [admin]
tags: [religion, wallace, berry, relativism, epistemology, ontology]
categories: []
date: 2013-08-20
lastmod: 2013-08-20
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

## Between Relativism and Universalism

First, it is important to start by saying that getting one’s beliefs correct is not, repeat not, the key to salvation (and we’ll discuss what I mean by salvation in a bit). One of the worst things that has happened to the church is that works-righteousness, the idea of earning ones way into heaven, was replaced not with grace, but with beliefs-righteousness, the idea that if one only believes the correct things fervently enough and without doubt one can earn their way into heaven.  Like works-righteousness, beliefs-righteousness leaves one with a constant feeling of guilt. Unlike works-righteousness, which at least led to good works being done, beliefs-righteousness leads to petty theological squabbles and lots of unnecessary hatred. Grace, by definition, is unearned. Apparently, however, this is too difficult of a concept for most people to grasp and so they decided they must be required to do something… if not works, then beliefs.

There’s one other thing to clear up at the outset. No one has all of it figured out. But before you panic and starting screaming “MORAL RELATIVISM!!” at the top of your lungs, the fact that no one belief is correct does not mean that anything goes. We’ll get into right and wrong more later in the post, but for now think of it like building a house. There is no one correct way to build a house; it depends on climate, personal preference, society, how many people are going to live there, etc. There are, however, plenty of wrong ways to build a house. If the house collapses, catches on fire, explodes, is cramped and uncomfortable, or is just generally the result of shoddy craftsmanship then it is a bad house. If your religious beliefs cause you to be full of hatred, hurt others, and/or are generally incoherent, self-contradictory, and not well thought out, then you have a bad set of religious beliefs. This, by the way, is not only true of religious beliefs. In most of life there is more than one correct way to do things, and there are also several incorrect ways. My claim is not that I have The Truth, but rather that I have a relatively well thought out and helpful belief system. It is (hopefully) a truth, just not The Truth.

## Why Believe Anything At All? 

I begin with a short joke from David Foster Wallace:

>There are these two young fish swimming along and they happen to meet an older fish swimming the other way, who nods at them and says “Morning, boys. How’s the water?” And the two young fish swim on for a bit, and then eventually one of them looks over at the other and goes, “What the hell is water?”

It is so inescapably true as to almost be banal that everything is about perspective, and our perspective limits us at least as much as it enlightens us. Perhaps the most important thing to understand is that you have a perspective. And there’s not much you can do about it. No one has put it better than Wallace in his commencement speech to Kenyon:

>Here is just one example of the total wrongness of something I tend to be automatically sure of: everything in my own immediate experience supports my deep belief that I am the absolute centre of the universe; the realest, most vivid and important person in existence. We rarely think about this sort of natural, basic self-centredness because it’s so socially repulsive. But it’s pretty much the same for all of us. It is our default setting, hard-wired into our boards at birth. Think about it: there is no experience you have had that you are not the absolute centre of. The world as you experience it is there in front of YOU or behind YOU, to the left or right of YOU, on YOUR TV or YOUR monitor. And so on. Other people’s thoughts and feelings have to be communicated to you somehow, but your own are so immediate, urgent, real.

Our default perspective is formed by our immediate experience. Now it’s possible to expand that a little bit. By listening to other people and actively cultivating empathy you might be able to get a taste, but only a taste, of what life is like for other people. The cold, hard truth, is that you will have to make decisions based on what you think is best. Whether you choose to believe in a God, the gods, virtue, human progress, sacred scripture, or nothing at all is up to you. There is no certainty available.  The one thing that is true is that you will have to choose, because trying not to choose is, in itself, a choice. It’s a choice to stick with the default setting, with our human wiring. Wallace writes,

>There is no such thing as not worshipping. Everybody worships. The only choice we get is what to worship. And the compelling reason for maybe choosing some sort of god or spiritual-type thing to worship–be it JC or Allah, be it YHWH or the Wiccan Mother Goddess, or the Four Noble Truths, or some inviolable set of ethical principles–is that pretty much anything else you worship will eat you alive. If you worship money and things, if they are where you tap real meaning in life, then you will never have enough, never feel you have enough. It’s the truth. Worship your body and beauty and sexual allure and you will always feel ugly.

>Worship power, you will end up feeling weak and afraid, and you will need ever more power over others to numb you to your own fear. Worship your intellect, being seen as smart, you will end up feeling stupid, a fraud, always on the verge of being found out. But the insidious thing about these forms of worship is not that they’re evil or sinful, it’s that they’re unconscious. They are default settings.

Our default settings rely on our own experiences of reality. Our own power, beauty, intellect, money, fame, things, place in society, and so on. There’s a good reason to move on from that default though and to consciously choose something to believe. Belief in this sense is not blind, but rather a conscious decision, a knowing leap of faith.

I’m going to move on to what I believe instead of just why I believe, but I encourage you to read Wallace’s [whole speech](https://www.economist.com/1843/2008/09/19/david-foster-wallace-in-his-own-words) (or [listen to it](https://www.youtube.com/watch?v=PhhC_N6Bm_s)).

## Being, Mystery, and Meaning

God does not exist. At least, not in the way that we normally think about existence. God does not exist in the same way that a cat or a building can be said to exist.

God is instead the source of existence and of meaning. The mysterious and unknown answer to the unanswerable questions: Why is there being at all instead of nothing? Why am I here?

These core philosophical/theological questions are ones that cannot, ultimately, be answered. I have found Gabriel Marcel helpful here in making an (admittedly somewhat arbitrary) distinction between problem and mystery:

>A problem is something which I meet, which I find completely before me, but which I can therefore lay siege to and reduce. But a mystery is something in which I am myself involved, and it can therefore only be thought of as a sphere where the distinction between what is in me and what is before me loses its meaning and initial validity.

A problem, conceived of this way, is like a jigsaw puzzle. All of the pieces are in front of you, and no matter who works on the puzzle the pieces will eventually fit together in the same way. A mystery, however, involves you. You cannot solve it because you are a part of it, and therefore you cannot attain an objective perspective. You can investigate a mystery, but it will change as you change.

When Albert Einstein spoke of religion, he spoke of mystery:

>The most beautiful experience we can have is the mysterious.  It is the fundamental emotion which stands at the cradle of all true art and science. Whoever does not know it and can no longer wonder, no longer marvel, is as good as dead, and his eyes are dimmed.  It was the experience of mystery – even if mixed with fear – that engendered religion.  A knowledge of the existence of something we cannot penetrate, our perceptions of the profoundest reason and the most radiant beauty, which only in their most primitive forms are accessible to our minds – it is this knowledge and this emotion that constitute true religiosity;  in this sense, and, and in this alone, I am a deeply religious man.

Formal religion is born, at least in part, from this religious experience. All too often, religion, like many human institutions, has failed miserably. Ironically, religion has sometimes even denied this religious experience of awe in favor of fear. Nonetheless, religion (broadly construed) has something essential to offer, a way of living that infuses our lives with meaning and allows us to see the sacred in the everyday.

## Choosing a Religion

There are two main reasons that I have chosen to remain Christian, and more specifically Lutheran (ELCA). To understand them you need to think of religion not as a set of beliefs but more in terms of a language and a story.

Thinking of religion as a language, I stay Lutheran because it is the religion in which I am fluent.  Within the faith tradition I grew up in there are powerful stories of exile, exodus, and resurrection. There are stories and parables of the ways in which a power beyond my understanding can transform death into life, and bring healing into the dark and broken corners of human existence. There are many examples of this sort of religious language being applied to life, but one of the most beautiful I have come across is Wendell Berry’s reflections on topsoil:

>The topsoil exists as such because it is ceaselessly transforming death into life, ceaselessly supplying food and water to all that lives in it and from it;….if we are to live well on and from our land, we must live by faith in the ceaselessness of these processes and by faith in our own willingness and ability to collaborate with them. Christ’s prayer for “daily bread” is an affirmation of such faith, just as it is a repudiation of faith in “much goods laid up.” Our life and livelihood are the gift of topsoil and of our willingness and ability to care for it, to grow good wheat, to make good bread; they do not derive from stockpiles of raw materials or accumulations of purchasing power.

The stories of the Bible have a great deal of meaning for me, and help me to understand the world around me. This is not to say that I do not borrow from other religions from time to time, much the way an English speaker might borrow a German word that expresses some interesting concept that does not exist in English. Nonetheless, Christianity is the language I am most fluent in, and therefore I remain Christian.

The other important reason is because I am a part of the story of Christianity. Quite simply, I am Christian because I grew up Christian. I used to see that as being an entirely insufficient reason because I was looking for some sort of universal and logical validation for my beliefs. Such certainty would be nice, but it simply is not available to human beings. Human beings are social creatures that construct meaning largely by telling stories. We tell stories about our own lives, about each other, about our ancestors, and about our religious beliefs. The stories of Christianity are now my stories.

## A Few Words on Salvation 

Salvation is not about life after death. It’s about this life. Let me say that again. Salvation is not about the afterlife, it’s about the here and now.  It is, once again, about how you perceive the world. Here’s the thing about the fish and the water. The water is there whether the fish know it or not. Salvation is a real possibility, a way of being in the world and a way of relating to other people. A way to avoid being eaten alive by the default gods of power, fame, wealth, and intellect. By the way, I didn’t just make that up, it comes in part from my faith tradition:

>The Kingdom of God is not coming with things that can be observed; nor will they say, ‘Look, here it is!’ or ‘There it is!’ For, in fact, the kingdom of God is among you. — Luke 17:20-21

Now, a lot of things have happened in Christian theology over the years, and there is no one definitive way to interpret the Bible. Nonetheless, Jesus clearly taught a way of life that had a lot to do with love, compassion, and prayer, and not as much to do with religious dogma (particularly when that dogma got in the way of compassion).

I have absolutely no idea what happens when we die, and don’t much care to speculate (although I will say I’m fairly sure it’s not a theology quiz). When I say that salvation is in this life I am not making a statement either way about the possibility of life after death. I am making a statement about this life, and how we have the very real possibility of living in awe of the mystery of life, the universe, and everything.

42

